User.create!(name:  "Akif")
User.create!(name:  "Retky")
User.create!(name:  "Fernando")
User.create!(name:  "Andres")
Car.create!(name: "BMW", model: "M3", desc: "The BMW M3 is a high-performant car  with various interior upgrades.", image: "https://raw.githubusercontent.com/CodeBitChips/Images/main/cars/bmw-m3.png", rent: "300.00")
Car.create!(name: "Ford", model: "Puma", desc: "The latest Puma model of Ford, launched with various interior upgrades.", image: "https://raw.githubusercontent.com/CodeBitChips/Images/main/cars/ford-puma.png", rent: "200.00")
Car.create!(name: "Hyundai", model: "Tucson", desc: "This Hyundai's new model release, the car you can dream of", image: "https://raw.githubusercontent.com/CodeBitChips/Images/main/cars/hyundai-tucson.png", rent: "500.00")
Car.create!(name: "Kia", model: "Sportage", desc: "The Kia Sportage provides a comfortable interior and a reliable safety.", image: "https://raw.githubusercontent.com/CodeBitChips/Images/main/cars/kia-sportage.png", rent: "400.00")
Reservation.create!(city: "New York", date: Date.parse("2020-01-01"), user_id: 1, car_id: 1)
Reservation.create!(city: "New York", date: Date.parse("2020-01-01"), user_id: 2, car_id: 2)
Reservation.create!(city: "New York", date: Date.parse("2020-01-01"), user_id: 3, car_id: 3)
Reservation.create!(city: "New York", date: Date.parse("2020-01-01"), user_id: 4, car_id: 4)
